/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Adversarial Candidate Ranking System API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdversaryConfig,
  AdversaryConfigInput,
  AuthResponse,
  Candidate,
  CandidateInput,
  DashboardStats,
  HealthStatus,
  JobDescription,
  JobInput,
  JobUpdate,
  ListCandidatesParams,
  LoginInput,
  ManipulationStats,
  MessageResponse,
  PerturbationType,
  RankingJob,
  RankingResults,
  RankingStartInput,
  RegisterInput,
  TrendDataPoint,
  User
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getRegisterUrl = () => {




  return `/api/auth/register`
}

/**
 * @summary Register new user
 */
export const register = async (registerInput: RegisterInput, options?: RequestInit): Promise<AuthResponse> => {

  return customFetch<AuthResponse>(getRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerInput)
  }
);}




export const getRegisterMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterInput>}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: BodyType<RegisterInput>}> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = BodyType<RegisterInput>
    export type RegisterMutationError = ErrorType<unknown>

    /**
 * @summary Register new user
 */
export const useRegister = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: BodyType<RegisterInput>},
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options));
    }

export const getLoginUrl = () => {




  return `/api/auth/login`
}

/**
 * @summary Login with email/password
 */
export const login = async (loginInput: LoginInput, options?: RequestInit): Promise<AuthResponse> => {

  return customFetch<AuthResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginInput)
  }
);}




export const getLoginMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: BodyType<LoginInput>}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = BodyType<LoginInput>
    export type LoginMutationError = ErrorType<unknown>

    /**
 * @summary Login with email/password
 */
export const useLogin = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: BodyType<LoginInput>},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options));
    }

export const getLogoutUrl = () => {




  return `/api/auth/logout`
}

/**
 * @summary Logout user
 */
export const logout = async ( options?: RequestInit): Promise<MessageResponse> => {

  return customFetch<MessageResponse>(getLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getLogoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {


          return  logout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>

    export type LogoutMutationError = ErrorType<unknown>

    /**
 * @summary Logout user
 */
export const useLogout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options));
    }

export const getGetMeUrl = () => {




  return `/api/auth/me`
}

/**
 * @summary Get current user
 */
export const getMe = async ( options?: RequestInit): Promise<User> => {

  return customFetch<User>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorType<unknown>


/**
 * @summary Get current user
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListJobsUrl = () => {




  return `/api/jobs`
}

/**
 * @summary List all job descriptions
 */
export const listJobs = async ( options?: RequestInit): Promise<JobDescription[]> => {

  return customFetch<JobDescription[]>(getListJobsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListJobsQueryKey = () => {
    return [
    `/api/jobs`
    ] as const;
    }


export const getListJobsQueryOptions = <TData = Awaited<ReturnType<typeof listJobs>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListJobsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listJobs>>> = ({ signal }) => listJobs({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData> & { queryKey: QueryKey }
}

export type ListJobsQueryResult = NonNullable<Awaited<ReturnType<typeof listJobs>>>
export type ListJobsQueryError = ErrorType<unknown>


/**
 * @summary List all job descriptions
 */

export function useListJobs<TData = Awaited<ReturnType<typeof listJobs>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listJobs>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListJobsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateJobUrl = () => {




  return `/api/jobs`
}

/**
 * @summary Create a new job description
 */
export const createJob = async (jobInput: JobInput, options?: RequestInit): Promise<JobDescription> => {

  return customFetch<JobDescription>(getCreateJobUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(jobInput)
  }
);}




export const getCreateJobMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJob>>, TError,{data: BodyType<JobInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createJob>>, TError,{data: BodyType<JobInput>}, TContext> => {

const mutationKey = ['createJob'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createJob>>, {data: BodyType<JobInput>}> = (props) => {
          const {data} = props ?? {};

          return  createJob(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateJobMutationResult = NonNullable<Awaited<ReturnType<typeof createJob>>>
    export type CreateJobMutationBody = BodyType<JobInput>
    export type CreateJobMutationError = ErrorType<unknown>

    /**
 * @summary Create a new job description
 */
export const useCreateJob = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJob>>, TError,{data: BodyType<JobInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createJob>>,
        TError,
        {data: BodyType<JobInput>},
        TContext
      > => {
      return useMutation(getCreateJobMutationOptions(options));
    }

export const getGetJobUrl = (id: number,) => {




  return `/api/jobs/${id}`
}

/**
 * @summary Get job description by ID
 */
export const getJob = async (id: number, options?: RequestInit): Promise<JobDescription> => {

  return customFetch<JobDescription>(getGetJobUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetJobQueryKey = (id: number,) => {
    return [
    `/api/jobs/${id}`
    ] as const;
    }


export const getGetJobQueryOptions = <TData = Awaited<ReturnType<typeof getJob>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJob>>> = ({ signal }) => getJob(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData> & { queryKey: QueryKey }
}

export type GetJobQueryResult = NonNullable<Awaited<ReturnType<typeof getJob>>>
export type GetJobQueryError = ErrorType<unknown>


/**
 * @summary Get job description by ID
 */

export function useGetJob<TData = Awaited<ReturnType<typeof getJob>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getJob>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetJobQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getUpdateJobUrl = (id: number,) => {




  return `/api/jobs/${id}`
}

/**
 * @summary Update job description
 */
export const updateJob = async (id: number,
    jobUpdate: JobUpdate, options?: RequestInit): Promise<JobDescription> => {

  return customFetch<JobDescription>(getUpdateJobUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(jobUpdate)
  }
);}




export const getUpdateJobMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJob>>, TError,{id: number;data: BodyType<JobUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateJob>>, TError,{id: number;data: BodyType<JobUpdate>}, TContext> => {

const mutationKey = ['updateJob'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateJob>>, {id: number;data: BodyType<JobUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateJob(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateJobMutationResult = NonNullable<Awaited<ReturnType<typeof updateJob>>>
    export type UpdateJobMutationBody = BodyType<JobUpdate>
    export type UpdateJobMutationError = ErrorType<unknown>

    /**
 * @summary Update job description
 */
export const useUpdateJob = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJob>>, TError,{id: number;data: BodyType<JobUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateJob>>,
        TError,
        {id: number;data: BodyType<JobUpdate>},
        TContext
      > => {
      return useMutation(getUpdateJobMutationOptions(options));
    }

export const getDeleteJobUrl = (id: number,) => {




  return `/api/jobs/${id}`
}

/**
 * @summary Delete job description
 */
export const deleteJob = async (id: number, options?: RequestInit): Promise<MessageResponse> => {

  return customFetch<MessageResponse>(getDeleteJobUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteJobMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJob>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteJob>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteJob'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteJob>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteJob(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteJobMutationResult = NonNullable<Awaited<ReturnType<typeof deleteJob>>>

    export type DeleteJobMutationError = ErrorType<unknown>

    /**
 * @summary Delete job description
 */
export const useDeleteJob = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJob>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteJob>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteJobMutationOptions(options));
    }

export const getListCandidatesUrl = (params?: ListCandidatesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/candidates?${stringifiedParams}` : `/api/candidates`
}

/**
 * @summary List all candidates
 */
export const listCandidates = async (params?: ListCandidatesParams, options?: RequestInit): Promise<Candidate[]> => {

  return customFetch<Candidate[]>(getListCandidatesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCandidatesQueryKey = (params?: ListCandidatesParams,) => {
    return [
    `/api/candidates`, ...(params ? [params] : [])
    ] as const;
    }


export const getListCandidatesQueryOptions = <TData = Awaited<ReturnType<typeof listCandidates>>, TError = ErrorType<unknown>>(params?: ListCandidatesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCandidates>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCandidatesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCandidates>>> = ({ signal }) => listCandidates(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCandidates>>, TError, TData> & { queryKey: QueryKey }
}

export type ListCandidatesQueryResult = NonNullable<Awaited<ReturnType<typeof listCandidates>>>
export type ListCandidatesQueryError = ErrorType<unknown>


/**
 * @summary List all candidates
 */

export function useListCandidates<TData = Awaited<ReturnType<typeof listCandidates>>, TError = ErrorType<unknown>>(
 params?: ListCandidatesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCandidates>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListCandidatesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateCandidateUrl = () => {




  return `/api/candidates`
}

/**
 * @summary Create a candidate
 */
export const createCandidate = async (candidateInput: CandidateInput, options?: RequestInit): Promise<Candidate> => {

  return customFetch<Candidate>(getCreateCandidateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(candidateInput)
  }
);}




export const getCreateCandidateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCandidate>>, TError,{data: BodyType<CandidateInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createCandidate>>, TError,{data: BodyType<CandidateInput>}, TContext> => {

const mutationKey = ['createCandidate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCandidate>>, {data: BodyType<CandidateInput>}> = (props) => {
          const {data} = props ?? {};

          return  createCandidate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCandidateMutationResult = NonNullable<Awaited<ReturnType<typeof createCandidate>>>
    export type CreateCandidateMutationBody = BodyType<CandidateInput>
    export type CreateCandidateMutationError = ErrorType<unknown>

    /**
 * @summary Create a candidate
 */
export const useCreateCandidate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCandidate>>, TError,{data: BodyType<CandidateInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCandidate>>,
        TError,
        {data: BodyType<CandidateInput>},
        TContext
      > => {
      return useMutation(getCreateCandidateMutationOptions(options));
    }

export const getGetCandidateUrl = (id: number,) => {




  return `/api/candidates/${id}`
}

/**
 * @summary Get candidate by ID
 */
export const getCandidate = async (id: number, options?: RequestInit): Promise<Candidate> => {

  return customFetch<Candidate>(getGetCandidateUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCandidateQueryKey = (id: number,) => {
    return [
    `/api/candidates/${id}`
    ] as const;
    }


export const getGetCandidateQueryOptions = <TData = Awaited<ReturnType<typeof getCandidate>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidate>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCandidate>>> = ({ signal }) => getCandidate(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCandidate>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCandidateQueryResult = NonNullable<Awaited<ReturnType<typeof getCandidate>>>
export type GetCandidateQueryError = ErrorType<unknown>


/**
 * @summary Get candidate by ID
 */

export function useGetCandidate<TData = Awaited<ReturnType<typeof getCandidate>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidate>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCandidateQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getDeleteCandidateUrl = (id: number,) => {




  return `/api/candidates/${id}`
}

/**
 * @summary Delete candidate
 */
export const deleteCandidate = async (id: number, options?: RequestInit): Promise<MessageResponse> => {

  return customFetch<MessageResponse>(getDeleteCandidateUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteCandidateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCandidate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCandidate>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCandidate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCandidate>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCandidate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCandidateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCandidate>>>

    export type DeleteCandidateMutationError = ErrorType<unknown>

    /**
 * @summary Delete candidate
 */
export const useDeleteCandidate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCandidate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteCandidate>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteCandidateMutationOptions(options));
    }

export const getStartRankingUrl = () => {




  return `/api/ranking/start`
}

/**
 * @summary Start a ranking job
 */
export const startRanking = async (rankingStartInput: RankingStartInput, options?: RequestInit): Promise<RankingJob> => {

  return customFetch<RankingJob>(getStartRankingUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rankingStartInput)
  }
);}




export const getStartRankingMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRanking>>, TError,{data: BodyType<RankingStartInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof startRanking>>, TError,{data: BodyType<RankingStartInput>}, TContext> => {

const mutationKey = ['startRanking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startRanking>>, {data: BodyType<RankingStartInput>}> = (props) => {
          const {data} = props ?? {};

          return  startRanking(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StartRankingMutationResult = NonNullable<Awaited<ReturnType<typeof startRanking>>>
    export type StartRankingMutationBody = BodyType<RankingStartInput>
    export type StartRankingMutationError = ErrorType<unknown>

    /**
 * @summary Start a ranking job
 */
export const useStartRanking = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRanking>>, TError,{data: BodyType<RankingStartInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof startRanking>>,
        TError,
        {data: BodyType<RankingStartInput>},
        TContext
      > => {
      return useMutation(getStartRankingMutationOptions(options));
    }

export const getGetRankingHistoryUrl = () => {




  return `/api/ranking/history`
}

/**
 * @summary Get ranking history
 */
export const getRankingHistory = async ( options?: RequestInit): Promise<RankingJob[]> => {

  return customFetch<RankingJob[]>(getGetRankingHistoryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRankingHistoryQueryKey = () => {
    return [
    `/api/ranking/history`
    ] as const;
    }


export const getGetRankingHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getRankingHistory>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRankingHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRankingHistoryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRankingHistory>>> = ({ signal }) => getRankingHistory({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRankingHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRankingHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getRankingHistory>>>
export type GetRankingHistoryQueryError = ErrorType<unknown>


/**
 * @summary Get ranking history
 */

export function useGetRankingHistory<TData = Awaited<ReturnType<typeof getRankingHistory>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRankingHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRankingHistoryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetRankingStatusUrl = (jobId: number,) => {




  return `/api/ranking/status/${jobId}`
}

/**
 * @summary Get ranking job status
 */
export const getRankingStatus = async (jobId: number, options?: RequestInit): Promise<RankingJob> => {

  return customFetch<RankingJob>(getGetRankingStatusUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRankingStatusQueryKey = (jobId: number,) => {
    return [
    `/api/ranking/status/${jobId}`
    ] as const;
    }


export const getGetRankingStatusQueryOptions = <TData = Awaited<ReturnType<typeof getRankingStatus>>, TError = ErrorType<unknown>>(jobId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRankingStatus>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRankingStatusQueryKey(jobId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRankingStatus>>> = ({ signal }) => getRankingStatus(jobId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: jobId !== null && jobId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRankingStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRankingStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getRankingStatus>>>
export type GetRankingStatusQueryError = ErrorType<unknown>


/**
 * @summary Get ranking job status
 */

export function useGetRankingStatus<TData = Awaited<ReturnType<typeof getRankingStatus>>, TError = ErrorType<unknown>>(
 jobId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRankingStatus>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRankingStatusQueryOptions(jobId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetRankingResultsUrl = (jobId: number,) => {




  return `/api/ranking/results/${jobId}`
}

/**
 * @summary Get complete ranking results
 */
export const getRankingResults = async (jobId: number, options?: RequestInit): Promise<RankingResults> => {

  return customFetch<RankingResults>(getGetRankingResultsUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRankingResultsQueryKey = (jobId: number,) => {
    return [
    `/api/ranking/results/${jobId}`
    ] as const;
    }


export const getGetRankingResultsQueryOptions = <TData = Awaited<ReturnType<typeof getRankingResults>>, TError = ErrorType<unknown>>(jobId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRankingResults>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRankingResultsQueryKey(jobId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRankingResults>>> = ({ signal }) => getRankingResults(jobId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: jobId !== null && jobId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRankingResults>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRankingResultsQueryResult = NonNullable<Awaited<ReturnType<typeof getRankingResults>>>
export type GetRankingResultsQueryError = ErrorType<unknown>


/**
 * @summary Get complete ranking results
 */

export function useGetRankingResults<TData = Awaited<ReturnType<typeof getRankingResults>>, TError = ErrorType<unknown>>(
 jobId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRankingResults>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRankingResultsQueryOptions(jobId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetAdversaryConfigUrl = () => {




  return `/api/adversary/config`
}

/**
 * @summary Get current adversary configuration
 */
export const getAdversaryConfig = async ( options?: RequestInit): Promise<AdversaryConfig> => {

  return customFetch<AdversaryConfig>(getGetAdversaryConfigUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdversaryConfigQueryKey = () => {
    return [
    `/api/adversary/config`
    ] as const;
    }


export const getGetAdversaryConfigQueryOptions = <TData = Awaited<ReturnType<typeof getAdversaryConfig>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdversaryConfig>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdversaryConfigQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdversaryConfig>>> = ({ signal }) => getAdversaryConfig({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdversaryConfig>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdversaryConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getAdversaryConfig>>>
export type GetAdversaryConfigQueryError = ErrorType<unknown>


/**
 * @summary Get current adversary configuration
 */

export function useGetAdversaryConfig<TData = Awaited<ReturnType<typeof getAdversaryConfig>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdversaryConfig>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdversaryConfigQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getUpdateAdversaryConfigUrl = () => {




  return `/api/adversary/config`
}

/**
 * @summary Update adversary configuration
 */
export const updateAdversaryConfig = async (adversaryConfigInput: AdversaryConfigInput, options?: RequestInit): Promise<AdversaryConfig> => {

  return customFetch<AdversaryConfig>(getUpdateAdversaryConfigUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adversaryConfigInput)
  }
);}




export const getUpdateAdversaryConfigMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdversaryConfig>>, TError,{data: BodyType<AdversaryConfigInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdversaryConfig>>, TError,{data: BodyType<AdversaryConfigInput>}, TContext> => {

const mutationKey = ['updateAdversaryConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdversaryConfig>>, {data: BodyType<AdversaryConfigInput>}> = (props) => {
          const {data} = props ?? {};

          return  updateAdversaryConfig(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdversaryConfigMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdversaryConfig>>>
    export type UpdateAdversaryConfigMutationBody = BodyType<AdversaryConfigInput>
    export type UpdateAdversaryConfigMutationError = ErrorType<unknown>

    /**
 * @summary Update adversary configuration
 */
export const useUpdateAdversaryConfig = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdversaryConfig>>, TError,{data: BodyType<AdversaryConfigInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateAdversaryConfig>>,
        TError,
        {data: BodyType<AdversaryConfigInput>},
        TContext
      > => {
      return useMutation(getUpdateAdversaryConfigMutationOptions(options));
    }

export const getGetPerturbationTypesUrl = () => {




  return `/api/adversary/perturbation-types`
}

/**
 * @summary Get available perturbation types
 */
export const getPerturbationTypes = async ( options?: RequestInit): Promise<PerturbationType[]> => {

  return customFetch<PerturbationType[]>(getGetPerturbationTypesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPerturbationTypesQueryKey = () => {
    return [
    `/api/adversary/perturbation-types`
    ] as const;
    }


export const getGetPerturbationTypesQueryOptions = <TData = Awaited<ReturnType<typeof getPerturbationTypes>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPerturbationTypes>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPerturbationTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPerturbationTypes>>> = ({ signal }) => getPerturbationTypes({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPerturbationTypes>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPerturbationTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getPerturbationTypes>>>
export type GetPerturbationTypesQueryError = ErrorType<unknown>


/**
 * @summary Get available perturbation types
 */

export function useGetPerturbationTypes<TData = Awaited<ReturnType<typeof getPerturbationTypes>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPerturbationTypes>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPerturbationTypesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetDashboardStatsUrl = () => {




  return `/api/analytics/dashboard`
}

/**
 * @summary Get dashboard statistics
 */
export const getDashboardStats = async ( options?: RequestInit): Promise<DashboardStats> => {

  return customFetch<DashboardStats>(getGetDashboardStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardStatsQueryKey = () => {
    return [
    `/api/analytics/dashboard`
    ] as const;
    }


export const getGetDashboardStatsQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardStats>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardStats>>> = ({ signal }) => getDashboardStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardStats>>>
export type GetDashboardStatsQueryError = ErrorType<unknown>


/**
 * @summary Get dashboard statistics
 */

export function useGetDashboardStats<TData = Awaited<ReturnType<typeof getDashboardStats>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDashboardStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetRankingTrendsUrl = () => {




  return `/api/analytics/trends`
}

/**
 * @summary Get ranking trends over time
 */
export const getRankingTrends = async ( options?: RequestInit): Promise<TrendDataPoint[]> => {

  return customFetch<TrendDataPoint[]>(getGetRankingTrendsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRankingTrendsQueryKey = () => {
    return [
    `/api/analytics/trends`
    ] as const;
    }


export const getGetRankingTrendsQueryOptions = <TData = Awaited<ReturnType<typeof getRankingTrends>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRankingTrends>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRankingTrendsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRankingTrends>>> = ({ signal }) => getRankingTrends({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRankingTrends>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRankingTrendsQueryResult = NonNullable<Awaited<ReturnType<typeof getRankingTrends>>>
export type GetRankingTrendsQueryError = ErrorType<unknown>


/**
 * @summary Get ranking trends over time
 */

export function useGetRankingTrends<TData = Awaited<ReturnType<typeof getRankingTrends>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRankingTrends>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRankingTrendsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetManipulationStatsUrl = () => {




  return `/api/analytics/manipulation`
}

/**
 * @summary Get manipulation detection statistics
 */
export const getManipulationStats = async ( options?: RequestInit): Promise<ManipulationStats> => {

  return customFetch<ManipulationStats>(getGetManipulationStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetManipulationStatsQueryKey = () => {
    return [
    `/api/analytics/manipulation`
    ] as const;
    }


export const getGetManipulationStatsQueryOptions = <TData = Awaited<ReturnType<typeof getManipulationStats>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getManipulationStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetManipulationStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getManipulationStats>>> = ({ signal }) => getManipulationStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getManipulationStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetManipulationStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getManipulationStats>>>
export type GetManipulationStatsQueryError = ErrorType<unknown>


/**
 * @summary Get manipulation detection statistics
 */

export function useGetManipulationStats<TData = Awaited<ReturnType<typeof getManipulationStats>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getManipulationStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetManipulationStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







