/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Adversarial Candidate Ranking System API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Register new user
 */
export const RegisterBody = zod.object({
  "email": zod.string(),
  "password": zod.string(),
  "fullName": zod.string(),
  "company": zod.string()
})

export const RegisterResponse = zod.object({
  "token": zod.string(),
  "user": zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "fullName": zod.string(),
  "company": zod.string(),
  "role": zod.string(),
  "createdAt": zod.string()
})
})


/**
 * @summary Login with email/password
 */
export const LoginBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
})

export const LoginResponse = zod.object({
  "token": zod.string(),
  "user": zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "fullName": zod.string(),
  "company": zod.string(),
  "role": zod.string(),
  "createdAt": zod.string()
})
})


/**
 * @summary Logout user
 */
export const LogoutResponse = zod.object({
  "message": zod.string()
})


/**
 * @summary Get current user
 */
export const GetMeResponse = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "fullName": zod.string(),
  "company": zod.string(),
  "role": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary List all job descriptions
 */
export const ListJobsResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "department": zod.string().nullish(),
  "experienceRequired": zod.number().nullish(),
  "skillsRequired": zod.array(zod.string()).optional(),
  "rawText": zod.string(),
  "createdAt": zod.string()
})
export const ListJobsResponse = zod.array(ListJobsResponseItem)


/**
 * @summary Create a new job description
 */
export const CreateJobBody = zod.object({
  "title": zod.string(),
  "department": zod.string().nullish(),
  "experienceRequired": zod.number().nullish(),
  "skillsRequired": zod.array(zod.string()).optional(),
  "rawText": zod.string()
})

export const CreateJobResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "department": zod.string().nullish(),
  "experienceRequired": zod.number().nullish(),
  "skillsRequired": zod.array(zod.string()).optional(),
  "rawText": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Get job description by ID
 */
export const GetJobParams = zod.object({
  "id": zod.coerce.number()
})

export const GetJobResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "department": zod.string().nullish(),
  "experienceRequired": zod.number().nullish(),
  "skillsRequired": zod.array(zod.string()).optional(),
  "rawText": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Update job description
 */
export const UpdateJobParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateJobBody = zod.object({
  "title": zod.string().optional(),
  "department": zod.string().nullish(),
  "experienceRequired": zod.number().nullish(),
  "skillsRequired": zod.array(zod.string()).optional(),
  "rawText": zod.string().optional()
})

export const UpdateJobResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "department": zod.string().nullish(),
  "experienceRequired": zod.number().nullish(),
  "skillsRequired": zod.array(zod.string()).optional(),
  "rawText": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Delete job description
 */
export const DeleteJobParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteJobResponse = zod.object({
  "message": zod.string()
})


/**
 * @summary List all candidates
 */
export const ListCandidatesQueryParams = zod.object({
  "jobId": zod.coerce.number().optional()
})

export const ListCandidatesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string().nullish(),
  "skills": zod.array(zod.string()).optional(),
  "experienceYears": zod.number().nullish(),
  "education": zod.string().nullish(),
  "rawText": zod.string(),
  "createdAt": zod.string()
})
export const ListCandidatesResponse = zod.array(ListCandidatesResponseItem)


/**
 * @summary Create a candidate
 */
export const CreateCandidateBody = zod.object({
  "name": zod.string(),
  "email": zod.string().nullish(),
  "skills": zod.array(zod.string()).optional(),
  "experienceYears": zod.number().nullish(),
  "education": zod.string().nullish(),
  "rawText": zod.string()
})

export const CreateCandidateResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string().nullish(),
  "skills": zod.array(zod.string()).optional(),
  "experienceYears": zod.number().nullish(),
  "education": zod.string().nullish(),
  "rawText": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Get candidate by ID
 */
export const GetCandidateParams = zod.object({
  "id": zod.coerce.number()
})

export const GetCandidateResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string().nullish(),
  "skills": zod.array(zod.string()).optional(),
  "experienceYears": zod.number().nullish(),
  "education": zod.string().nullish(),
  "rawText": zod.string(),
  "createdAt": zod.string()
})


/**
 * @summary Delete candidate
 */
export const DeleteCandidateParams = zod.object({
  "id": zod.coerce.number()
})

export const DeleteCandidateResponse = zod.object({
  "message": zod.string()
})


/**
 * @summary Start a ranking job
 */
export const StartRankingBody = zod.object({
  "jdId": zod.number(),
  "candidateIds": zod.array(zod.number())
})

export const StartRankingResponse = zod.object({
  "id": zod.number(),
  "jdId": zod.number().optional(),
  "status": zod.enum(['pending', 'running', 'completed', 'failed']),
  "progress": zod.number(),
  "totalCandidates": zod.number(),
  "jobTitle": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Get ranking history
 */
export const GetRankingHistoryResponseItem = zod.object({
  "id": zod.number(),
  "jdId": zod.number().optional(),
  "status": zod.enum(['pending', 'running', 'completed', 'failed']),
  "progress": zod.number(),
  "totalCandidates": zod.number(),
  "jobTitle": zod.string().nullish(),
  "createdAt": zod.string()
})
export const GetRankingHistoryResponse = zod.array(GetRankingHistoryResponseItem)


/**
 * @summary Get ranking job status
 */
export const GetRankingStatusParams = zod.object({
  "jobId": zod.coerce.number()
})

export const GetRankingStatusResponse = zod.object({
  "id": zod.number(),
  "jdId": zod.number().optional(),
  "status": zod.enum(['pending', 'running', 'completed', 'failed']),
  "progress": zod.number(),
  "totalCandidates": zod.number(),
  "jobTitle": zod.string().nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Get complete ranking results
 */
export const GetRankingResultsParams = zod.object({
  "jobId": zod.coerce.number()
})

export const GetRankingResultsResponse = zod.object({
  "jobId": zod.number(),
  "rankedCandidates": zod.array(zod.object({
  "candidateId": zod.number(),
  "name": zod.string(),
  "finalScore": zod.number(),
  "fitScore": zod.number(),
  "robustnessScore": zod.number(),
  "stabilityScore": zod.number(),
  "ranking": zod.number(),
  "isRobust": zod.boolean(),
  "manipulationRisk": zod.enum(['low', 'medium', 'high']).optional(),
  "redFlags": zod.array(zod.object({
  "type": zod.string(),
  "severity": zod.enum(['low', 'medium', 'high']),
  "details": zod.string()
})),
  "skillsMatch": zod.object({
  "matched": zod.array(zod.string()),
  "missing": zod.array(zod.string()),
  "extra": zod.array(zod.string())
}).optional(),
  "explanation": zod.string(),
  "recommendation": zod.enum(['strong_hire', 'hire', 'consider', 'reject']),
  "strengths": zod.array(zod.string()).optional(),
  "gaps": zod.array(zod.string()).optional(),
  "adversarialTests": zod.array(zod.object({
  "perturbationType": zod.string(),
  "originalRank": zod.number(),
  "perturbedRank": zod.number(),
  "positionChange": zod.number()
})).optional()
})),
  "summary": zod.object({
  "totalCandidates": zod.number(),
  "flaggedForManipulation": zod.number(),
  "highlyRobust": zod.number(),
  "averageRobustness": zod.number(),
  "timeTaken": zod.string()
})
})


/**
 * @summary Get current adversary configuration
 */
export const GetAdversaryConfigResponse = zod.object({
  "id": zod.number().optional(),
  "numVariants": zod.number(),
  "intensity": zod.enum(['low', 'medium', 'high']),
  "enabledPerturbations": zod.array(zod.string())
})


/**
 * @summary Update adversary configuration
 */
export const UpdateAdversaryConfigBody = zod.object({
  "numVariants": zod.number().optional(),
  "intensity": zod.enum(['low', 'medium', 'high']).optional(),
  "enabledPerturbations": zod.array(zod.string()).optional()
})

export const UpdateAdversaryConfigResponse = zod.object({
  "id": zod.number().optional(),
  "numVariants": zod.number(),
  "intensity": zod.enum(['low', 'medium', 'high']),
  "enabledPerturbations": zod.array(zod.string())
})


/**
 * @summary Get available perturbation types
 */
export const GetPerturbationTypesResponseItem = zod.object({
  "key": zod.string(),
  "label": zod.string(),
  "description": zod.string()
})
export const GetPerturbationTypesResponse = zod.array(GetPerturbationTypesResponseItem)


/**
 * @summary Get dashboard statistics
 */
export const GetDashboardStatsResponse = zod.object({
  "totalCandidates": zod.number(),
  "totalJobs": zod.number(),
  "totalRankings": zod.number(),
  "flaggedProfiles": zod.number(),
  "highlyRobust": zod.number(),
  "averageScore": zod.number(),
  "recentRankings": zod.array(zod.object({
  "id": zod.number(),
  "jdId": zod.number().optional(),
  "status": zod.enum(['pending', 'running', 'completed', 'failed']),
  "progress": zod.number(),
  "totalCandidates": zod.number(),
  "jobTitle": zod.string().nullish(),
  "createdAt": zod.string()
})).optional()
})


/**
 * @summary Get ranking trends over time
 */
export const GetRankingTrendsResponseItem = zod.object({
  "date": zod.string(),
  "totalRankings": zod.number(),
  "flaggedCount": zod.number(),
  "robustCount": zod.number(),
  "averageScore": zod.number()
})
export const GetRankingTrendsResponse = zod.array(GetRankingTrendsResponseItem)


/**
 * @summary Get manipulation detection statistics
 */
export const GetManipulationStatsResponse = zod.object({
  "keywordStuffing": zod.number(),
  "experienceInflation": zod.number(),
  "promptInjection": zod.number(),
  "irrelevantSkills": zod.number(),
  "total": zod.number()
})


